[project]
name = "subscription-control"
version = "0.1.0"
description = "Initial code for a personal project aiming to create a simple subscription and payment system using essential Python tools"
authors = [
    {name = "Fábio Radicchi Belotto", email = "fabio_belotto@hotmail.com"}
]
license = "NPOSL-3.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "httpx>=0.28.1",
    "pydantic[email]>=2.10.6",
    "pydantic-settings>=2.8.1",
    "sqlalchemy>=2.0.39",
    "uvicorn>=0.34.0",
]

[dependency-groups]
dev = [
    "aiosqlite>=0.21.0",
    "ipykernel>=6.29.5",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
]

[tool.uv]
python-downloads = "manual"
